services:
  - type: worker
    name: nhentai-telegram-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
